on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test Cmake Container
    strategy:
      fail-fast: true
      matrix:
        containerbase: ["gcc-ubuntu-20.04", "clang-ubuntu-20.04", "cuda-ubuntu-20.04"]
        flags: ["-DENABLE_OPENMP=On", "-DENABLE_OPENMP=On", "-DENABLE_CUDA=On"]

    name: "${{ matrix.containerbase }} ${{ matrix.flags }}"
    steps:
    - name: Build and run testing container
      env:
        WORKDIR=${{ inputs.workdir }}
      run: |
         cd cmake/
         docker build --build-arg containerbase=ghcr.io/rse-radiuss/${{ matrix.containerbase }} --build-arg flags=${{ matrix.flags }} -t cmake-testing-container ${{ inputs.context }}
